### PR TITLE
Loved using your app

### PR DESCRIPTION
**Pull request by ThisIsBis**
Picked up this low hanging fruit - https://github.com/insin/vlc_remote/issues/7

### CODE REVIEW

**Comment by ThisIsBis** [comment]
Driving the interface using the results from the playlist API. This decouples the App from any changes to the playlist made outside the app. Please give it a spin to check it out.

**Comment by ThisIsBis** [comment]
Added few more changes:
1. Playlist focused interface
Playlist Updates

2. Added new items in popup menu (also fixed a bug there)
Popup Changes

**Comment by insin** [comment]
@ThisIsBis this looks great, will give it a spin when I get some time this weeken

**Comment by ThisIsBis** [comment]
> @ThisIsBis this looks great, will give it a spin when I get some time this weekend

How are your tests going?

**Comment by insin** [comment]
Merged into master, thanks for all the fixes and features 😍

Will try to get a new version released this week

**Pull request merged**
